name: krx feed

on:
  schedule:
    - cron: "15 1 * * 1-5"   # 평일 10:15 KST (UTC+9 = 01:15 UTC)
  workflow_dispatch: {}       # 수동 실행 버튼

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -U pip
          pip install playwright pandas lxml html5lib requests beautifulsoup4
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: |
          python krx_scrape.py

      - name: Commit artifacts
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A out/
          git commit -m "update feed" || echo "nothing to commit"
          git push

    # .github/workflows/krx-feed.yml 의 마지막 커밋 스텝 교체
      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          add: "out/*.csv out/html/*.html"
          message: "auto: update feed"
          default_author: github_actions

      # 선택: HTML을 잡아서 아티팩트로도 저장
      - name: Upload HTML debug
        uses: actions/upload-artifact@v4
        with:
          name: html-debug
          path: out/html/*.html
      
